services:
  - docker

install:
  - docker pull gamedrivendesign/godot-export

script:
  - docker run -e EXPORT_NAME="HTML5" -e OUTPUT_FILENAME="index.html" -v $(pwd):/build/src -v $(pwd)/output/html5:/build/output gamedrivendesign/godot-export
  - docker run -e EXPORT_NAME="Linux/X11" -e OUTPUT_FILENAME="harederlage" -v $(pwd):/build/src -v $(pw)/output/linux:/build/output gamedrivendesign/godot-export

before_deploy:
  - zip harederlage-linux.zip output/linux/*

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      local-dir: output/html5

  - provider: releases
    api-key: $GITHUB_TOKEN
    file: harederlage-linux.zip
    skip-cleanup: true
    on:
      tags: true
