sudo: false

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_x11.64.zip -O /tmp/godot.zip
  - unzip -q -d /tmp /tmp/godot.zip
  - mv /tmp/Godot* /tmp/godot

script:
  - /tmp/godot --export "HTML5" --path . output/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: output
