sudo: required

services:
  - docker

install:
  - docker pull gamedrivendesign/godot-export

script:
  - docker run -e EXPORT_NAME="HTML5" -e OUTPUT_FILENAME="index.html" -v $(pwd):/build/src -v /tmp/output:/build/output gamedrivendesign/godot-export

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: /tmp/output

