sudo: required

services:
  - docker

install:
  - docker build -t gamedrivendevelopment/godot .

script:
  - docker run -v `pwd`:/tmp/build gamedrivendevelopment/godot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: /tmp/build/output

