sudo: required

services:
  - docker

install:
  - docker build -t gamedrivendesign/godot .

script:
  - docker run -v /tmp/output:/tmp/build/output gamedrivendesign/godot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: /tmp/output

