sudo: required
dist: trusty
os:
- linux
services:
  - docker

before_install:
  - docker pull mattiascibien/godot-docker:3.0.2

script:
  - docker run -v "$(pwd):/game" mattiascibien/godot-docker:3.0.2 /bin/sh -c "godot --export 'HTML5' --path /game /game/output/index.html"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: output
